import HeaderAdmin from '@/shared/components/headerAdmin'
import type { NextPage } from 'next'
import Head from 'next/head'

const AdminDashboard: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Admin | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderAdmin />
    </div>
  )
}

export default AdminDashboard
