import ClientHeader from '@/shared/components/clientHeader'
import { Box, Text } from '@chakra-ui/react'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { useTranslation } from 'react-i18next'

function Restaurants() {
  const { t } = useTranslation()
  return (
    <div>
      <div>
        <Head>
          <title>Foody | {t('restaurants')}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Box className="max-w-[1440px] mx-auto">
          <header>
            <ClientHeader />
          </header>
          <main className="flex mx-8">
            <section className="">
              <Box className="w-64 h-lvh bg-client-fill-gray flex flex-col max-h-[620px] scrollbar overflow-y-scroll pr-4">
                <Box>
                  <Image
                    width={25}
                    height={28}
                    alt="resto"
                    src="https://media-cdn.tripadvisor.com/media/photo-p/16/f6/e2/8d/mixed-beef.jpg"
                  />
                  <Text className="text-xl font-semibold"></Text>
                </Box>
              </Box>
            </section>
            <section>
              <Box></Box>
            </section>
          </main>
          <footer></footer>
        </Box>
      </div>
    </div>
  )
}

export default Restaurants

export async function getStaticProps({ locale }: { locale: any }) {
  return {
    props: { ...(await serverSideTranslations(locale, ['admin'])) },
  }
}
