// import type { NextPage } from 'next'
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import axios from 'axios'

// import ClientHeader from '@/shared/components/clientHeader'
// // import { Box } from '@chakra-ui/react'
// import { useTranslation } from 'react-i18next'
// import AdminModalButton from '@/shared/components/adminModalButton'
// import { useRouter } from 'next/router'
// import { serverSideTranslations } from 'next-i18next/serverSideTranslations'





// const Home: NextPage = () => {
//   const { t } = useTranslation('client')

//   const navigate = useRouter()



//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Foody | Home</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       {/* <Box className="max-w-[1440px] mx-auto"> */}
//       <header className='   bg-client-fill-gray m-0 sm:m-8 flex-col rounded-md '>
//         <ClientHeader />
//         <div className='flex flex-col-reverse  sm:flex-row  justify-center  items-center  h-screen  px-1 sm:px-11  -mt-24'>
//           <div className='w-full sm:w-1/2   flex flex-col  gap-9' >
//             <h1 className=' text-6xl text-center sm:text-5xl font-black leading-tight sm:text-start text-client-manin-black'>Our Food site makes it easy to find local food</h1>
//             <p className='sm:block hidden     sm:text-xl  w-3/4    text-client-main-gray1'>Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.</p>
//             <div className='mx-auto sm:mx-0 flex gap-10 w-max'>
//               <AdminModalButton text={t('Register')} className='  bg-client-main-red  text-white text-2xl px-8 py-3 rounded-3xl  font-medium shadow-md hover:bg-red-700 hover:scale-95 transition-all duration-500' onClick={() => navigate.push("/login")} />
//               <AdminModalButton text={t('OrderNow')} className='  rounded-3xl border-client-main-gray1  border-2  px-6 py-3    text-client-main-gray1  text-2xl font-medium shadow-md hover:scale-95 transition-all duration-500' onClick={() => navigate.push("/restaurants")} />
//             </div>
//           </div>
//           <div className='sm:w-3/5'>
//             <div className={styles.burger_bg}></div>
//             <div className={`${styles.little_animation_div1}`}>
//               <Image width={70} height={0} src='/frenchFries.svg' alt="frenchFries" />
//               <p className='w-1/2 text-center'>French Fries
//                 Yummy...</p>
//             </div>
//             <div className={`${styles.little_animation_div2}`}>
//               <Image width={70} height={0} src='/pizzaHut.svg' alt="pizza" />
//               <p className='w-1/2 text-center'>Pizza Hut
//                 Yummy ...</p>
//             </div>
//             <div className={`${styles.little_animation_div3}`}>
//               <Image width={70} height={0} src='/cheesBurger.svg' alt="cheesBurger" />
//               <p className='w-1/2 text-center'>Cheesburger
//                 Yummy ...</p>
//             </div>
//             <Image width={0} height={0} src='/bigBurgerMain.svg' alt="bigBurger" className='relative   w-full' />
//           </div>
//         </div>
//       </header>
//       <main>
//         <section className='className="flex flex-col gap-10 justify-center my-14 px-3 sm:px-14"'>
//           <div className='flex flex-col items-center  gap-4 text-center mb-12'>
//             <h2 className=" text-4xl   font-extrabold   text-client-manin-black">{t("Features")}</h2>
//             <p className="     text-client-main-gray1 w-full sm:w-2/3 text-2xl">
//               Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
//             </p>
//           </div>

//           <div className='flex flex-col sm:flex-row justify-center items-center gap-14 '>
//             <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
//               <Image width={238} height={0} src='/discountBoucher.svg' alt='discount' className='mx-auto' />
//               <p className=' text-client-main-gray2  text-3xl font-bold '>Discount Boucher</p>
//               <p className=' text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder  commonly used in the graphic </p>
//             </div>

//             <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
//               <Image width={238} height={0} src='/healthyFood.svg' alt='healthyFood' className='mx-auto' />
//               <p className=' text-client-main-gray2  text-3xl font-bold '>Fresh healthy Food</p>
//               <p className=' text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder  commonly used in the graphic </p>
//             </div>

//             <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
//               <Image width={238} height={0} src='/fastHomeDelivery.svg' alt='fastHome' className='mx-auto' />
//               <p className=' text-client-main-gray2  text-3xl font-bold '>Fast Home Delivery</p>
//               <p className=' text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder  commonly used in the graphic </p>
//             </div>
//           </div>
//         </section>


//         <section className="flex flex-col sm:flex-row justify-center items-center px-3 sm:px-11 mt-52">
//           <div className="flex flex-col gap-8 w-full sm:w-1/2">
//             <h3 className="text-5xl     font-black text-client-manin-black w-full sm:w-full sm:text-6xl  leading-tight text-center  mx-auto sm:mx-0 sm:text-start">
//               Menu That Always Make You Fall In Love
//             </h3>
//             <p className="  text-client-main-gray1    font-normal    text-xl w-full mb-8 sm:mb-0 sm:w-3/5 mx-auto text-center sm:text-start sm:mx-0">
//               Lorem ipsum is placeholder text commonly used in the graphic,
//               print, and publishing industries for previewing layouts and visual
//               mockups.Lorem ipsum is placeholder text commonly used in the
//               graphic, print, and publishing industries for previewing layouts
//               and visual mockups.
//             </p>
//           </div>
//           <div className='relative w-full sm:w-1/2 sm:mt-48'>
//             <Image
//               className="w-full"
//               width={0}
//               height={0}
//               src={"kfcHome.svg"}
//               alt="kfc"
//             />
//             <Image
//               className='w-full absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2'
//               width={0}
//               height={0}
//               src="/kfc.svg"
//               alt="kf"
//             />
//           </div>
//         </section>

//         <section className="flex flex-col sm:flex-row justify-center items-center px-3 sm:px-11 mt-52">
//           <div className="flex flex-col gap-8 w-full sm:w-1/2">
//             <h3 className="text-5xl     font-black text-client-manin-black w-full sm:w-full sm:text-6xl  leading-tight text-center  mx-auto sm:mx-0 sm:text-start">
//               Menu That Always Make You Fall In Love
//             </h3>
//             <p className="  text-client-main-gray1    font-normal    text-xl w-full mb-8 sm:mb-0 sm:w-3/5 mx-auto text-center sm:text-start sm:mx-0">
//               Lorem ipsum is placeholder text commonly used in the graphic,
//               print, and publishing industries for previewing layouts and visual
//               mockups.Lorem ipsum is placeholder text commonly used in the
//               graphic, print, and publishing industries for previewing layouts
//               and visual mockups.
//             </p>
//           </div>
//           <div className='relative w-full sm:w-1/2 sm:mt-48'>
//             <Image
//               className="w-full"
//               width={0}
//               height={0}
//               src={"papaPizzaHome.svg"}
//               alt="pizza"
//             />
//             <Image
//               className='w-full absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2'
//               width={0}
//               height={0}
//               src="/papaPizza.svg"
//               alt="pizza"
//             />
//           </div>
//         </section>


//         <section className='className="flex flex-col gap-10 justify-center my-14 px-3 sm:px-14"'>
//           <div className='flex flex-col items-center  gap-4 text-center mb-12'>
//             <h2 className=" text-4xl   font-extrabold   text-client-manin-black">{t("Our Popular Update New Foods")}</h2>
//             <p className="     text-client-main-gray1 w-full sm:w-2/3 text-2xl">
//               Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
//             </p>
//           </div>

//           <div className='flex flex-col sm:flex-row justify-center items-center gap-14 '>
//             <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
//               <Image width={238} height={0} src='/dubbleChees.svg' alt='dubbleChees' className='mx-auto' />
//               <p className=' text-client-main-gray2  text-3xl font-bold '>Dubble Chees</p>
//               <p className=' text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder  commonly used in the graphic </p>
//             </div>

//             <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
//               <Image width={238} height={0} src='/margarita.svg' alt='margarita' className='mx-auto' />
//               <p className=' text-client-main-gray2  text-3xl font-bold '>Margarita</p>
//               <p className=' text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder  commonly used in the graphic </p>
//             </div>

//             <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
//               <Image width={238} height={0} src='/twister.svg' alt='twister' className='mx-auto' />
//               <p className=' text-client-main-gray2  text-3xl font-bold '>Twister Menu</p>
//               <p className=' text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder  commonly used in the graphic </p>
//             </div>
//           </div>
//         </section>

//         {/* <section className="w-3/4 flex justify-around   bg-client-black27 absolute  items-center rounded-3xl py-12 px-0 sm:px-9 text-white ">
//           <Image
//             className="hidden sm:block"
//             width={200}
//             height={0}
//             src={"/footerPizza.svg"}
//             alt="pizza"
//           />

//           <div className="flex flex-col items-center gap-5">
//             <p className=" font-medium text-xl sm:text-4xl w-9/12 text-center leading-tight">
//               {t("")}
//             </p>
//             <button className="   bg-client-main-orange px-12 py-4 font-medium text-md rounded-full hover:scale-95 transition-all duration-500">
//               {t("button")}
//             </button>
//           </div>

//           <Image
//             className="hidden sm:block"
//             width={250}
//             height={0}
//             src={"/footerBurger.svg"}
//             alt="burger"
//           />
//         </section> */}



//       </main>
//       {/* </Box> */}
//     </div>
//   )
// }

// export default Home

// export async function getStaticProps({ locale }: { locale: any }) {
//   return {
//     props: { ...(await serverSideTranslations(locale, ['client'])) },
//   }
// }

import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import ClientHeader from '@/shared/components/clientHeader'
import { useTranslation } from 'react-i18next'
import AdminModalButton from '@/shared/components/adminModalButton'
import { useRouter } from 'next/router'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useState } from 'react'

const Home: NextPage = () => {
  const { t } = useTranslation('client')
  const navigate = useRouter()
  const [data, setData] = useState([]);



  return (
    <div className={styles.container}>
      <Head>
        <title>Foody | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='bg-client-fill-gray m-0 sm:m-8 flex-col rounded-md'>
        <ClientHeader />
        <div className='flex flex-col-reverse sm:flex-row justify-center items-center h-screen px-1 sm:px-11 -mt-24'>
          <div className='w-full sm:w-1/2 flex flex-col gap-9'>
            <h1 className='sm:text-6xl text-center   text-2xl font-black leading-tight sm:text-start text-client-manin-black'>
              {/* {t("homeHeading")} */}Our Food site makes it easy to find local food
            </h1>
            <p className='sm:block hidden sm:text-xl w-3/4 text-client-main-gray1'>
              Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
            </p>
            <div className='mx-auto flex-col sm:flex-row sm:mx-0 flex gap-10 w-max'>
              <AdminModalButton text={t('Register')} className='bg-client-main-red text-white   text-lg sm:text-2xl sm:px-8  px-12 py-3 rounded-[30px] font-medium shadow-md hover:bg-red-700 hover:scale-95 transition-all duration-500' onClick={() => navigate.push("/login")} />
              <AdminModalButton text={t('OrderNow')} className='rounded-[30px] border-client-main-gray1 border-2 sm:px-8  px-12 py-3 text-client-main-gray1 text-lg sm:text-2xl font-medium shadow-md hover:scale-95 transition-all duration-500' onClick={() => navigate.push("/restaurants")} />
            </div>
          </div>
          <div className='sm:w-3/5 relative    mt-0 pt-0  flex justify-center '>
            <div className={`${styles.bg_black}`}>
              <div className={`${styles.french}`}>
                <Image width={60} height={0} src='/frenchFries.svg' alt="frenchFries" />
                <p className='w-1/2 text-center'>French Fries Yummy...</p>
              </div>
            </div>

            <div className={`${styles.pizza}`}>
              <Image width={60} height={0} src='/pizzaHut.svg' alt="pizza" />
              <p className='w-1/2 text-center'>Pizza Hut Yummy ...</p>
            </div>
            <div className={`${styles.cheesBurger}`}>
              <Image width={60} height={0} src='/cheesBurger.svg' alt="cheesBurger" />
              <p className='w-1/2 text-center'>Cheesburger Yummy ...</p>
            </div>
            <Image width={0} height={0} src='/bigBurgerMain.svg' alt="bigBurger" className='relative sm:w-full w-[80%]  ' />
          </div>
        </div>
      </header>


      {/* main section */}
      <main>
        <section className='flex flex-col gap-10 justify-center my-14 px-3 sm:px-14'>
          <div className='flex flex-col items-center gap-4 text-center mb-12'>
            <h2 className='text-4xl font-extrabold text-client-manin-black'>{t("features")}</h2>
            <p className='text-client-main-gray1 w-full sm:w-2/3 text-2xl'>
              Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
            </p>
          </div>

          <div className='flex flex-col sm:flex-row justify-center items-center gap-14'>
            <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
              <Image width={220} height={0} src='/discountBoucher.svg' alt='discount' className='mx-auto' />
              <p className='text-client-main-gray2 text-3xl font-bold'>Discount Boucher</p>
              <p className='text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder commonly used in the graphic</p>
            </div>
            <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
              <Image width={220} height={0} src='/healthyFood.svg' alt='healthyFood' className='mx-auto' />
              <p className='text-client-main-gray2 text-3xl font-bold'>Fresh healthy Food</p>
              <p className='text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder commonly used in the graphic</p>
            </div>
            <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
              <Image width={220} height={0} src='/fastHomeDelivery.svg' alt='fastHome' className='mx-auto' />
              <p className='text-client-main-gray2 text-3xl font-bold'>Fast Home Delivery</p>
              <p className='text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder commonly used in the graphic</p>
            </div>
          </div>
        </section>

        <section className='flex flex-col sm:flex-row justify-center items-center px-3 sm:px-11 mt-52'>
          <div className='flex flex-col gap-8 w-full sm:w-1/2'>
            <h3 className='text-5xl font-black text-client-manin-black w-full sm:w-full sm:text-6xl leading-tight text-center mx-auto sm:mx-0 sm:text-start'>
              Menu That Always Make You Fall In Love
            </h3>
            <p className='text-client-main-gray1 font-normal text-xl w-full mb-8 sm:mb-0 sm:w-3/5 mx-auto text-center sm:text-start sm:mx-0'>
              Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
            </p>
          </div>
          <div className='relative w-full sm:w-1/2 sm:mt-48'>
            <Image className='w-full' width={0} height={0} src={"kfcHome.svg"} alt="kfc" />
            <Image className='w-full absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2' width={0} height={0} src="/kfc.svg" alt="kf" />
          </div>
        </section>

        <section className='flex flex-col sm:flex-row-reverse justify-center items-center px-3 sm:px-11 mt-52'>
          <div className='flex flex-col gap-8 w-full sm:w-1/2'>
            <h3 className='text-5xl font-black text-client-manin-black w-full sm:w-full sm:text-6xl leading-tight text-center mx-auto sm:mx-0 sm:text-start'>
              Menu That Always Make You Fall In Love
            </h3>
            <p className='text-client-main-gray1 font-normal text-xl w-full mb-8 sm:mb-0 sm:w-3/5 mx-auto text-center sm:text-start sm:mx-0'>
              Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
            </p>
          </div>
          <div className='relative w-full sm:w-1/2 sm:mt-48'>
            <Image className='w-full' width={0} height={0} src={"papaPizzaHome.svg"} alt="pizza" />
            <Image className='w-full absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2' width={0} height={0} src="/papaPizza.svg" alt="pizza" />
          </div>
        </section>
        {/*  */}
        <section className='flex flex-col sm:flex-row justify-center items-center px-3 sm:px-11 mt-52'>
          <div className='flex flex-col gap-8 w-full sm:w-1/2'>
            <h3 className='text-5xl font-black text-client-manin-black w-full sm:w-full sm:text-6xl leading-tight text-center mx-auto sm:mx-0 sm:text-start'>
              Menu That Always Make You Fall In Love
            </h3>
            <p className='text-client-main-gray1 font-normal text-xl w-full mb-8 sm:mb-0 sm:w-3/5 mx-auto text-center sm:text-start sm:mx-0'>
              Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
            </p>
          </div>
          <div className='relative w-full sm:w-1/2 sm:mt-48'>
            <Image className='w-full' width={0} height={0} src="/frencHomeRectangle.svg" alt="french" />
            <Image className='w-full absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2' width={0} height={0} src={"/frenchHome.svg"} alt="frenchFries" />
          </div>
        </section>

        <section className='flex flex-col gap-10 justify-center my-14 px-3 sm:px-14'>
          <div className='flex flex-col items-center gap-4 text-center mb-12'>
            <h2 className='text-4xl font-extrabold text-client-manin-black'>{t("Our Popular Update New Foods")}</h2>
            <p className='text-client-main-gray1 w-full sm:w-2/3 text-2xl'>
              Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.
            </p>
          </div>
          <div className='flex flex-col sm:flex-row justify-center items-center gap-14'>
            <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
              <Image width={220} height={0} src='/dubbleChees.svg' alt='dubbleChees' className='mx-auto' />
              <p className='text-client-main-gray2 text-3xl font-bold'>Dubble Chees</p>
              <p className='text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder commonly used in the graphic</p>
            </div>
            <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
              <Image width={220} height={0} src='/margarita.svg' alt='margarita' className='mx-auto' />
              <p className='text-client-main-gray2 text-3xl font-bold'>Margarita</p>
              <p className='text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder commonly used in the graphic</p>
            </div>
            <div className='flex flex-col gap-6 text-center pb-7 shadow-xl'>
              <Image width={220} height={0} src='/twister.svg' alt='twister' className='mx-auto' />
              <p className='text-client-main-gray2 text-3xl font-bold'>Twister Menu</p>
              <p className='text-client-main-gray1 w-2/3 mx-auto text-lg font-normal'>Lorem ipsum is placeholder commonly used in the graphic</p>
            </div>
          </div>
        </section>


        <section className="w-3/4 flex justify-around   bg-client-black27 absolute  items-center rounded-3xl py-12 px-0 sm:px-12  text-white ">
          <Image
            className="hidden sm:block sm:w-4/12"
            width={200}
            height={0}
            src={"/footerPizza.svg"}
            alt="pizza"
          />
          <div className="flex flex-col items-center gap-5">
            <p className=" font-medium   text-lg sm:text-4xl w-9/12 text-center leading-tight">
              {t("Discover Restaurants Near From you")}
            </p>
            <button className="   bg-client-main-orange px-14 py-4 font-medium text-md rounded-[30px] hover:scale-95 transition-all duration-500       ">
              {t("Explore now")}
            </button>
          </div>

          <Image
            className="hidden sm:block sm:w-4/12"
            width={250}
            height={0}
            src={"/footerBurger.svg"}
            alt="burger"
          />
        </section>
      </main>
    </div>
  )
}

export default Home

export async function getStaticProps({ locale }: { locale: any }) {
  return {
    props: { ...(await serverSideTranslations(locale, ['client'])) },
  }
}

