import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import ClientHeader from '@/shared/components/client/clientHeader'
import { useTranslation } from 'react-i18next'
import AdminModalButton from '@/shared/components/admin/adminModalButton'
import { useRouter } from 'next/router'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

import { useQuery } from '@tanstack/react-query'
import { getOffers } from '@/shared/services/offers'
import ClientFooter from '@/shared/components/client/clientFooter'
import { useEffect } from 'react'
import AOS from 'aos'
import 'aos/dist/aos.css'
import ClientLayout from '@/shared/components/layout/clientLayout'
import HomeOfferCard from '@/shared/components/client/homeOfferCard/homeOfferCard'
import { Offer, Product } from '@/shared/types/admin'
import { QUERY } from '@/shared/constants/query'
import { getProducts } from '@/shared/services/products'
import HomeProductCard from '@/shared/components/client/homeProductCard/homeProductCard'

const Home: NextPage = () => {
  const { t } = useTranslation('client')
  const navigate = useRouter()

  const { data } = useQuery({
    queryFn: getOffers,
    queryKey: [QUERY.OFFER],
  })

  const offersData: Offer[] = data?.data?.result?.data

  const { data: product } = useQuery({
    queryFn: getProducts,
    queryKey: [QUERY.PRODUCTS],
  })

  const productData: Product[] = product?.data?.result?.data

  useEffect(() => {
    AOS.init({ duration: 2000 })
  }, [])

  return (
    <div className="overflow-x-hidden">
      <Head>
        <title>Foody | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-client-fill-gray m-0 sm:m-8 flex-col rounded-md">
        <ClientHeader />
        <div className="flex flex-col-reverse sm:flex-row justify-center items-center h-screen px-1 sm:px-11 -mt-24">
          <div
            data-aos="fade-up"
            className="w-full sm:w-1/2 flex flex-col gap-9"
          >
            <h1 className="sm:text-6xl text-center   text-2xl font-black leading-tight sm:text-start text-client-manin-black">
              {/* {t("homeHeading")} */}Our Food site makes it easy to find
              local food
            </h1>
            <p className="sm:block hidden sm:text-xl w-3/4 text-client-main-gray1">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups.
            </p>
            <div className="mx-auto flex-col sm:flex-row sm:mx-0 flex gap-10 w-max">
              <AdminModalButton
                text={t('Register')}
                className="bg-client-main-red text-white   text-lg sm:text-2xl sm:px-8  px-12 py-3 rounded-[30px] font-medium shadow-md   hover:scale-95 transition-all duration-500    hover:bg-client-main-orange"
                onClick={() => navigate.push('/login')}
              />
              <AdminModalButton
                text={t('OrderNow')}
                className="rounded-[30px] border-client-main-gray1 border-2 sm:px-8  px-12 py-3 text-client-main-gray1 text-lg sm:text-2xl font-medium shadow-md hover:scale-95 transition-all duration-500"
                onClick={() => navigate.push('/restaurants')}
              />
            </div>
          </div>
          <div
            data-aos="fade-right"
            className="sm:w-3/5 relative    mt-0 pt-0  flex justify-center "
          >
            <div className={`${styles.bg_black}`}>
              <div className={`${styles.french}`}>
                <Image
                  width={60}
                  height={0}
                  src="/frenchFries.svg"
                  alt="frenchFries"
                />
                <p className="w-1/2 text-center">French Fries Yummy...</p>
              </div>
            </div>

            <div className={`${styles.pizza}`}>
              <Image width={60} height={0} src="/pizzaHut.svg" alt="pizza" />
              <p className="w-1/2 text-center">Pizza Hut Yummy ...</p>
            </div>
            <div className={`${styles.cheesBurger}`}>
              <Image
                width={60}
                height={0}
                src="/cheesBurger.svg"
                alt="cheesBurger"
              />
              <p className="w-1/2 text-center">Cheesburger Yummy ...</p>
            </div>
            <Image
              width={0}
              height={0}
              src="/bigBurgerMain.svg"
              alt="bigBurger"
              className="relative sm:w-full w-[80%]  "
            />
          </div>
        </div>
      </header>

      {/* main section */}
      <main>
        <section className="flex flex-col gap-10 justify-center my-14 px-3 sm:px-14">
          <div
            data-aos="flip-up"
            className="flex flex-col items-center gap-4 text-center mb-12"
          >
            <h2 className="text-4xl font-extrabold text-client-manin-black">
              {t('features')}
            </h2>
            <p className="text-client-main-gray1 w-full sm:w-2/3 text-2xl">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row justify-center items-center gap-14 sm:gap-6 lg:gap-[72px]">
            {productData?.slice(3, 6)?.map((product, index) => {
              return (
                <HomeProductCard product={product} index={index} key={index} />
              )
            })}
          </div>
        </section>

        <section className="max-w-[1380px] flex flex-col mx-auto sm:mt-56">
          {offersData?.map((offer, index) => {
            if (index % 2 === 1) {
              return <HomeOfferCard offer={offer} key={index} index={index} />
            }
            return <HomeOfferCard offer={offer} key={index} index={index} />
          })}
        </section>

        <section className="flex flex-col gap-10 justify-center my-14 px-3 sm:px-14">
          <div
            data-aos="flip-up"
            className="flex flex-col items-center gap-4 text-center mb-12"
          >
            <h2 className="text-4xl font-extrabold text-client-manin-black">
              {t('Our Popular Update New Foods')}
            </h2>
            <p className="text-client-main-gray1 w-full sm:w-2/3 text-2xl">
              Lorem ipsum is placeholder text commonly used in the graphic,
              print, and publishing industries for previewing layouts and visual
              mockups.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row justify-center items-center gap-14 sm:gap-6 lg:gap-[72px]">
            {productData?.slice(0, 3)?.map((product, index) => {
              return (
                <HomeProductCard product={product} index={index} key={index} />
              )
            })}
          </div>
        </section>
      </main>

      <section data-aos="flip-down" className={`w-7/12 ${styles.footer_to_bg}`}>
        <Image
          className="hidden sm:block sm:w-4/12"
          width={200}
          height={0}
          src={'/footerPizza.svg'}
          alt="pizza"
        />
        <div className="flex flex-col items-center gap-5">
          <p className=" font-medium   text-lg sm:text-4xl w-9/12 text-center leading-tight">
            {t('Discover Restaurants Near From you')}
          </p>
          <button className="bg-client-main-orange px-14 py-4 font-medium text-md rounded-[30px] hover:scale-95 transition-all duration-500">
            {t('Explore now')}
          </button>
        </div>

        <Image
          className="hidden sm:block sm:w-4/12"
          width={250}
          height={0}
          src={'/footerBurger.svg'}
          alt="burger"
        />
      </section>

      <ClientFooter />
    </div>
  )
}

export default Home

export async function getStaticProps({ locale }: { locale: any }) {
  return {
    props: { ...(await serverSideTranslations(locale, ['client'])) },
  }
}

{
  /* <div
              data-aos="slide-right"
              className="flex flex-col gap-6 text-center pb-7 shadow-xl"
            >
              <Image
                width={220}
                height={0}
                src="/dubbleChees.svg"
                alt="dubbleChees"
                className="mx-auto"
              />
              <p className="text-client-main-gray2 text-3xl font-bold">
                Dubble Chees
              </p>
              <p className="text-client-main-gray1 w-2/3 mx-auto text-lg font-normal">
                Lorem ipsum is placeholder commonly used in the graphic
              </p>
            </div> */
}

{
  /* <div
              data-aos="slide-up"
              className="flex flex-col gap-6 text-center pb-7 shadow-xl"
            >
              <Image
                width={220}
                height={0}
                src="/margarita.svg"
                alt="margarita"
                className="mx-auto"
              />
              <p className="text-client-main-gray2 text-3xl font-bold">
                Margarita
              </p>
              <p className="text-client-main-gray1 w-2/3 mx-auto text-lg font-normal">
                Lorem ipsum is placeholder commonly used in the graphic
              </p>
            </div> */
}

{
  /* <div
              data-aos="slide-left"
              className="flex flex-col gap-6 text-center pb-7 shadow-xl"
            >
              <Image
                width={220}
                height={0}
                src="/twister.svg"
                alt="twister"
                className="mx-auto"
              />
              <p className="text-client-main-gray2 text-3xl font-bold">
                Twister Menu
              </p>
              <p className="text-client-main-gray1 w-2/3 mx-auto text-lg font-normal">
                Lorem ipsum is placeholder commonly used in the graphic
              </p>
            </div> */
}

{
  /* <div
              data-aos="slide-right"
              className="flex flex-col gap-6 text-center pb-7 shadow-xl"
            >
              <Image
                width={220}
                height={0}
                src="/discountBoucher.svg"
                alt="discount"
                className="mx-auto"
              />
              <p className="text-client-main-gray2 text-3xl font-bold">
                Discount Boucher
              </p>
              <p className="text-client-main-gray1 w-2/3 mx-auto text-lg font-normal">
                Lorem ipsum is placeholder commonly used in the graphic
              </p>
            </div>
            <div
              data-aos="slide-up"
              className="flex flex-col gap-6 text-center pb-7 shadow-xl"
            >
              <Image
                width={220}
                height={0}
                src="/healthyFood.svg"
                alt="healthyFood"
                className="mx-auto"
              />
              <p className="text-client-main-gray2 text-3xl font-bold">
                Fresh healthy Food
              </p>
              <p className="text-client-main-gray1 w-2/3 mx-auto text-lg font-normal">
                Lorem ipsum is placeholder commonly used in the graphic
              </p>
            </div>
            <div
              data-aos="slide-left"
              className="flex flex-col gap-6 text-center pb-7 shadow-xl"
            >
              <Image
                width={220}
                height={0}
                src="/fastHomeDelivery.svg"
                alt="fastHome"
                className="mx-auto"
              />
              <p className="text-client-main-gray2 text-3xl font-bold">
                Fast Home Delivery
              </p>
              <p className="text-client-main-gray1 w-2/3 mx-auto text-lg font-normal">
                Lorem ipsum is placeholder commonly used in the graphic
              </p>
            </div> */
}
